version: '3.8'
services:
  service-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/clients_db

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clients_db
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped